/// Flutter icons NicoyaNowIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NicoyaNowIcons
///      fonts:
///       - asset: fonts/NicoyaNowIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NicoyaNowIcons {
  NicoyaNowIcons._();

  static const _kFontFam = 'NicoyaNowIcons';
  static const String? _kFontPkg = null;

  static const IconData basurero = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flechaderecha = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flechaizquierda = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lupa = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subirarchivo = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portapapeles = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campana = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audifonos = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ubicacion = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pedido = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flechaizquierda2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plato = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menos = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dolar = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mas = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carritocompras = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmodal = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usuario = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timelapsecocinando = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timelapserecivirorden = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timelapserepartidor = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reloj = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timelapsecheck = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editar = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maletatrabajo = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nicoyanow = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
